esphome:
  name: irrigation-system

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "passwordhere"

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ssidhere"
    password: "passwordhere"

captive_portal:

switch:
  - platform: gpio
    name: "Zone 1"
    id: relay_1
    pin: 18
    inverted: true

  - platform: gpio
    name: "Zone 2"
    id: relay_2
    pin: 19
    inverted: true

  - platform: gpio
    name: "Zone 3"
    id: relay_3
    pin: 21
    inverted: true

  - platform: gpio
    name: "Zone 4"
    id: relay_4
    pin: 22
    inverted: true

  - platform: gpio
    name: "Zone 5"
    id: relay_5
    pin: 23
    inverted: true

  - platform: gpio
    name: "Zone 6"
    id: relay_6
    pin: 25
    inverted: true

  - platform: gpio
    name: "Zone 7"
    id: relay_7
    pin: 26
    inverted: true

  - platform: gpio
    name: "Zone 8"
    id: relay_8
    pin: 27
    inverted: true

interval:
  - interval: 15s
    then:
    - if:
        condition:
          wifi.connected:
        then:
        else:
          - switch.turn_off: relay_1
          - switch.turn_off: relay_2
          - switch.turn_off: relay_3
          - switch.turn_off: relay_4
          - switch.turn_off: relay_5
          - switch.turn_off: relay_6
          - switch.turn_off: relay_7
          - switch.turn_off: relay_8